"""Download an unseen generator dataset (ProGAN) and populate val_unseen_generator.

This script fetches 1,000 images generated by ProGAN (NVIDIA Progressive GAN)
from Hugging Face into `data/raw/ai/progan/` and runs `data/prepare.py` with
`--holdout-generators progan`.
"""

from __future__ import annotations

import io
from pathlib import Path
import subprocess
import sys
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parent.parent
TARGET_DIR = ROOT / "data" / "raw" / "ai" / "progan"
ZIP_FILES = [
    "https://huggingface.co/datasets/frp94/progan_val/resolve/main/bird.zip",
    "https://huggingface.co/datasets/frp94/progan_val/resolve/main/car.zip",
    "https://huggingface.co/datasets/frp94/progan_val/resolve/main/dog.zip",
]


def main() -> None:
    TARGET_DIR.mkdir(parents=True, exist_ok=True)

    existing_images = list(TARGET_DIR.glob("*.jpg")) + list(TARGET_DIR.glob("*.png"))
    target_count = 2000
    if len(existing_images) >= target_count:
        print(f"Found {len(existing_images)} existing images in {TARGET_DIR}.", flush=True)
    else:
        print(f"Currently have {len(existing_images)} images. Fetching more to reach {target_count} ProGAN images...", flush=True)
        count = len(existing_images)
        for url in ZIP_FILES:
            if count >= target_count:
                break
            print(f"Fetching from {url}...", flush=True)
            req = urllib.request.urlopen(url)
            content = req.read()
            print(f"Downloaded {len(content) / (1024 * 1024):.1f} MB. Extracting...", flush=True)
            
            with zipfile.ZipFile(io.BytesIO(content)) as zf:
                namelist = [f for f in zf.namelist() if f.lower().endswith((".jpg", ".png", ".jpeg"))]
                for name in namelist:
                    if count >= target_count:
                        break
                    data = zf.read(name)
                    out_path = TARGET_DIR / f"progan_{count:04d}.png"
                    out_path.write_bytes(data)
                    count += 1
        print(f"Successfully saved total of {count} ProGAN images into {TARGET_DIR}", flush=True)

    print("\nRe-building dataset splits with --holdout-generators progan...", flush=True)
    cmd = [sys.executable, str(ROOT / "data" / "prepare.py"), "--holdout-generators", "progan"]
    subprocess.run(cmd, check=True)

    print("\nFinished! You can now run `.venv/bin/python model/evaluate.py`!", flush=True)


if __name__ == "__main__":
    main()
